name: wbabich
favicon: null
layout_spectrum: 0.7706458049360663
typography_spectrum: 0.26983035495504737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.657068244414404
  lightness: 0.5091433881316334
  saturation: 0.6986942847725004
  rhythmicContrast: 0.20734512526541948
purpose: []
