name: Walker Babich
favicon: null
layout_spectrum: 0.7706458049360663
typography_spectrum: 0.26983035495504737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000302'
    - '#f0f9ff'
    - '#293751'
    - '#9bb0df'
    - '#636758'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
