name: Walker Babich
favicon: null
layout_spectrum: 0.89929
typography_spectrum: 0.48008
title: Adventure
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74651885-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000302'
    - '#f0f9ff'
    - '#293751'
    - '#9bb0df'
    - '#636758'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
