name: Walker Babich
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25459
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000302'
    - '#f0f9ff'
    - '#293751'
    - '#9bb0df'
    - '#636758'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
